version: "3.5"

services:
  fluent:
    image: fluent/fluent-bit:2.1.4-debug
    volumes:
      - ./fluentbit/:/fluent-bit/etc/
    ports:
      - "30000:30000"
    restart: always
  mosquitto:
    image: eclipse-mosquitto:2.0
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
    ports:
      - 1883:1883
    restart: always
