version: "3.5"

services:
  fluent:
    image: fluent/fluent-bit:2.1.4-debug
    volumes:
      - ./fluentbit/:/fluent-bit/etc/
    ports:
      - "30000:30000"
    restart: always
    depends_on:
      - kafka
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto:2.0
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
    ports:
      - 1883:1883
    restart: always
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://deeprasp:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  ksql:
    image: bitnami/ksql
    environment:
      - KSQL_BOOTSTRAP_SERVERS=deeprasp:9092
      - KSQL_LISTENERS=http://0.0.0.0:8088
