version: "3.5"

services:
  timescale:
    image: timescale/timescaledb:latest-pg15
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: data
      POSTGRES_USER: "${psql_user}"
      POSTGRES_PASSWORD: "${psql_pass}"
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${psql_user}" ]
      interval: 10s
      timeout: 5s
      retries: 10
  fluent:
    image: fluent/fluent-bit
    volumes:
      - ./fluentbit/:/fluent-bit/etc/
    ports:
      - "30000:30000"
    depends_on:
      timescale:
        condition: service_healthy
